dist: trusty
sudo: required
language: python
python:
 - '2.7'
 - '3.5'

matrix:
 allow_failures:
  - python: '3.3'

before_install:
 - sudo apt-get install libfuse-dev
 - sudo apt-get install libnetcdf-dev

install:
 - pip install --upgrade pip
 - pip install -r requirements.txt

script:
 - python -m unittest test.test_ncfs
 - py.test --pep8

notifications:
  email: false
